### ISSUE TITLE
Differing font sizes for ON

### ISSUE THREAD

**Issue by dirtydancing** [jameshome/anduril-guide#2]
In `Simple UI`, the `ON` ahead of `immediate Turbo` (marked red in the attached screenshot) is smaller in font size than the other three `ON` (marked green). This might extend to more than only the `ON`, but that is hard to tell, and I only noticed this slight visual inconsistency for `ON`.

![ON](https://user-images.githubusercontent.com/7164227/221274479-39435318-70b9-4308-97ed-ddb322cc6bf1.png)

**Comment by jameshome** [comment]
Deeply appreciate your attention to detail!
