### ISSUE TITLE
Overheating? 13H Reset

### ISSUE THREAD

**Issue by dirtydancing** [jameshome/anduril-guide#3]
In accordance with https://github.com/jameshome/anduril-guide/issues/1, obviously also the other reference to `Reset` underneath `Thermal config` would need to be changed from `13C` to `13H` (cf. attached screenshot).

![13H](https://user-images.githubusercontent.com/7164227/221357658-ba778d29-a30c-4cb5-a618-12aae6fd0e70.png)

**Comment by jameshome** [comment]
Would have missed this for sure if you hadn't specifically noted it. Thank you!
