### ISSUE TITLE
Visual connection between 3C Toggle and ON

### ISSUE THREAD

**Issue by dirtydancing** [jameshome/anduril-guide#5]
An immediate visual connection between `3C Toggle ramp style` (from `ON`) and the vertical `ON` line is missing, cf. this screenshot:

![3C_ON_a](https://user-images.githubusercontent.com/7164227/221380038-320af037-befa-429e-a0dd-edf880e22a8f.png)

Recently, this resulted in me going down the vertical `ON` line in search of `3C`, and it taking me a while to actually locate it. To remedy this, it might be helpful to add a corresponding horizontal line between the vertical `ON` line and `3C Toggle ramp style`, e.g. as displayed in this illustration:

![3C_ON_b](https://user-images.githubusercontent.com/7164227/221380067-515ca94e-9fea-412d-b307-893f8fd87d66.png)

At the same time, this would also visually clarify instantly that `3C Toggle ramp style` relates to `ON` and not to `OFF`.

**Comment by jameshome** [comment]
This was really bugging me too.
